### ISSUE TITLE
Error to unregister connector at the Metadata Broker

### ISSUE THREAD

**Issue by jfernandezsqs** [International-Data-Spaces-Association/DataspaceConnector#311]
I have deployed a Dataspace Connector version 7.1.0 and registered this connector to the Metadata Broker successfully.
I perform the call `POST /api/ids/connector/update` and it is registered the connector at the Metadata Broker
```
2022-06-17T09:21:23,793 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-06-17T10:11:21.000+0000)]
2022-06-17T09:21:23,811 [https-jsse-nio-8080-exec-2] INFO - Successfully loaded Keystore.
2022-06-17T09:21:23,866 [https-jsse-nio-8080-exec-2] INFO - Successfully loaded Truststore.
2022-06-17T09:21:23,871 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-06-17T10:11:21.000+0000)]
2022-06-17T09:21:23,891 [https-jsse-nio-8080-exec-2] INFO - Sending request to https://broker-reverseproxy/infrastructure ...
2022-06-17T09:21:24,755 [https-jsse-nio-8080-exec-2] INFO - Successfully received response to request.
2022-06-17T09:21:24,765 [https-jsse-nio-8080-exec-2] INFO - Successfully passed SHACL-Validation.
2022-06-17T09:21:24,803 [https-jsse-nio-8080-exec-2] INFO - Requesting public key of token issuer. [url=(http://omejdn/auth/jwks.json), kid=(b5dac7d64831047f7395d8362aa575b1e908eedbf1e5c500bee184558cacbd97)]
2022-06-17T09:21:24,818 [https-jsse-nio-8080-exec-2] INFO - Successfully validated DAPS whitelisting.
2022-06-17T09:21:24,819 [https-jsse-nio-8080-exec-2] INFO - Successfully verified DAT claims.
2022-06-17T09:21:24,856 [https-jsse-nio-8080-exec-2] INFO - Successfully updated connector. [url=(https://broker-reverseproxy/infrastructure})]
```

However, when I try to unregister the connector from the Metadata Broker using the call `POST /api/ids/connector /unavailable` it gives me the following error:
```
2022-06-17T09:27:09,339 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-06-17T10:11:21.000+0000)]
2022-06-17T09:27:09,353 [https-jsse-nio-8080-exec-2] INFO - Successfully loaded Keystore.
2022-06-17T09:27:09,407 [https-jsse-nio-8080-exec-2] INFO - Successfully loaded Truststore.
2022-06-17T09:27:09,411 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-06-17T10:11:21.000+0000)]
2022-06-17T09:27:09,424 [https-jsse-nio-8080-exec-2] INFO - Sending request to https://broker-reverseproxy/infrastructure ...
2022-06-17T09:27:09,541 [https-jsse-nio-8080-exec-2] INFO - Successfully received response to request.
2022-06-17T09:27:09,548 [https-jsse-nio-8080-exec-2] INFO - Successfully passed SHACL-Validation.
2022-06-17T09:27:09,579 [https-jsse-nio-8080-exec-2] DEBUG - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/INTERNAL_RECIPIENT_ERROR, payload=An unknown error has occurred, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]
```

These are all the logs obtained from the DSC and the MDB;
```
connectora             | 2022-06-17T09:27:09,339 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-06-17T10:11:21.000+0000)]
connectora             | 2022-06-17T09:27:09,353 [https-jsse-nio-8080-exec-2] INFO - Successfully loaded Keystore.
connectora             | 2022-06-17T09:27:09,407 [https-jsse-nio-8080-exec-2] INFO - Successfully loaded Truststore.
connectora             | 2022-06-17T09:27:09,411 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-06-17T10:11:21.000+0000)]
connectora             | 2022-06-17T09:27:09,424 [https-jsse-nio-8080-exec-2] INFO - Sending request to https://broker-reverseproxy/infrastructure ...
omejdn-server          | 172.18.0.8 - - [17/Jun/2022:09:27:09 +0000] "GET /jwks.json HTTP/1.1" 200 469 0.0012
omejdn                 | 172.18.0.3 - - [17/Jun/2022:09:27:09 +0000] "GET /.well-known/jwks.json HTTP/1.1" 200 469 "-" "Java/11.0.13" "-"
broker-core            | 09:27:09.521 [http-nio-8080-exec-7] INFO  de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.ClaimsVerifier - Verifying token's claims
broker-core            | java.lang.NullPointerException
broker-core            | 	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ConnectorUnavailableValidationStrategy.validate(ConnectorUnavailableValidationStrategy.java:56)
broker-core            | 	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ConnectorUnavailableValidationStrategy.validate(ConnectorUnavailableValidationStrategy.java:21)
broker-core            | 	at de.fraunhofer.iais.eis.ids.connector.commons.messagevalidation.ValidatingMessageHandler.handle(ValidatingMessageHandler.java:21)
broker-core            | 	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.handle(MessageDispatcher.java:86)
broker-core            | 	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.lambda$dispatch$2(MessageDispatcher.java:51)
broker-core            | 	at java.base/java.util.Optional.map(Optional.java:265)
broker-core            | 	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.dispatch(MessageDispatcher.java:51)
broker-core            | 	at de.fraunhofer.iais.eis.ids.component.core.DefaultComponent.process(DefaultComponent.java:45)
broker-core            | 	at de.fraunhofer.iais.eis.ids.component.interaction.multipart.MultipartComponentInteractor.process(MultipartComponentInteractor.java:87)
broker-core            | 	at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.processMessage(ComponentController.java:237)
broker-core            | 	at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.infrastructureLevelCommunication(ComponentController.java:205)
broker-core            | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
broker-core            | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
broker-core            | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
broker-core            | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
broker-core            | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
broker-core            | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
broker-core            | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
broker-core            | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
broker-core            | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
broker-core            | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
broker-core            | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
broker-core            | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
broker-core            | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
broker-core            | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
broker-core            | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
broker-core            | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
broker-core            | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core            | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core            | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
broker-core            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core            | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
broker-core            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core            | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
broker-core            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core            | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
broker-core            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core            | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
broker-core            | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
broker-core            | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
broker-core            | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
broker-core            | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
broker-core            | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
broker-core            | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
broker-core            | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
broker-core            | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
broker-core            | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
broker-core            | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
broker-core            | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
broker-core            | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
broker-core            | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
broker-core            | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
broker-core            | 	at java.base/java.lang.Thread.run(Thread.java:829)
broker-reverseproxy    | 172.18.0.7 - - [17/Jun/2022:09:27:09 +0000] "POST /infrastructure HTTP/1.1" 200 2918 "-" "okhttp/4.9.3"
connectora             | 2022-06-17T09:27:09,541 [https-jsse-nio-8080-exec-2] INFO - Successfully received response to request.
connectora             | 2022-06-17T09:27:09,548 [https-jsse-nio-8080-exec-2] INFO - Successfully passed SHACL-Validation.
connectora             | 2022-06-17T09:27:09,579 [https-jsse-nio-8080-exec-2] DEBUG - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/INTERNAL_RECIPIENT_ERROR, payload=An unknown error has occurred, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]
```

**Comment by ghost** [comment]
Reading from the logs, there is a `NullPointerException` thrown by the `broker-core`'s `ConnectorUnavailableValidationStrategy` class. I will forward this accordingly and discuss internally how we proceed.

**Comment by SebastianOpriel** [comment]
@rmsoyta @TasneemRashid do you have an idea, what possibly could go wrong at 
`de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.ClaimsVerifier - Verifying token's claims
broker-core            | java.lang.NullPointerException`?

**Comment by timwirtz86** [comment]
@jfernandezsqs thanks you for the information. Would it be possible for you to catch the message the Connector send? This would help understanding the exception in more detail. Currently we are puzzeled by the behavior, as we didn't saw it in our tests.

**Comment by jfernandezsqs** [comment]
These are the logs the DSC is generating:
```
2022-06-17T09:27:09,339 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-06-17T10:11:21.000+0000)]
2022-06-17T09:27:09,353 [https-jsse-nio-8080-exec-2] INFO - Successfully loaded Keystore.
2022-06-17T09:27:09,407 [https-jsse-nio-8080-exec-2] INFO - Successfully loaded Truststore.
2022-06-17T09:27:09,411 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-06-17T10:11:21.000+0000)]
2022-06-17T09:27:09,424 [https-jsse-nio-8080-exec-2] INFO - Sending request to https://broker-reverseproxy/infrastructure ...
2022-06-17T09:27:09,541 [https-jsse-nio-8080-exec-2] INFO - Successfully received response to request.
2022-06-17T09:27:09,548 [https-jsse-nio-8080-exec-2] INFO - Successfully passed SHACL-Validation.
2022-06-17T09:27:09,579 [https-jsse-nio-8080-exec-2] DEBUG - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/INTERNAL_RECIPIENT_ERROR, payload=An unknown error has occurred, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]
```
If you want to replicate the scenario execute the `docker-compose.yml` of the [IDS-testbed](https://github.com/International-Data-Spaces-Association/IDS-testbed).
Then, enter in the DataspaceconnectorA  `https://localhost:8080/api/docs` and execute:

1) Register to the MetadataBroker
    POST /api/ids/connector/update
    with recipient --> `https://broker-reverseproxy/infrastructure`
2) Unregister to the MetadataBroker
    POST /api/ids/connector/unavailable 
    with recipient --> `https://broker-reverseproxy/infrastructure`
